### PR TITLE
Bug fixes and removed useless stuff

### PR DESCRIPTION
**Pull request by malsvn**
- Fixed `bot` argument (not needed since we are using a selfbot package)
- Removed useless imports from `ghost.py`
- Removed the chunking of guilds at startup which may slow down the overall selfbot performance
- Fixed commands not actually working due to them needing to be awaited

What issues the old version had (yours)
- Commands were not added [example shown here](https://imgur.com/a/vl4rdzS)
- Useless imports (may be slowing down performance)
- Had `bot` argument from `run()` when it wasn't a known argument by `discord.py-self`

Edited:
- Improved README by adding a fix for `Improper Token Passed`

### CODE REVIEW

**Comment by malsvn** [comment]
Also fixed useless discord.py-self logging

**Comment by bennyscripts** [comment]
The "useless imports" are used for the script system, since the scripts are read and then ran through the main file all the imports need to be there. If you bring back the imports I'll consider merging.

**Comment by malsvn** [comment]
oh okay my bad hold on

**Comment by malsvn** [comment]
should have the imports now

**Comment by Euro-pol** [comment]
Thanks

**Comment by malsvn** [comment]
> Thanks

💯💯💯💯💯

**Comment by bennyscripts** [comment]
I have just recently pushed a lot of new edits and fixes which now makes this pull request redundant.

**Pull request closed without merging**
