### PR TITLE
Optimized typing notifier by making it spam less.

### PR DESCRIPTION
**Pull request by jbsparrow**
Also added a N/A option in the computer stats command for users who don't have a GPU.

### CODE REVIEW

**Comment by bentettmar** [comment]
I don't see how it would prevent from spamming. It looks like all its doing is adding a new time to a dictionary. Do you have any result from testing?

**Comment by jbsparrow** [comment]
Yes. It will not send a typing notification for the same user typing until a two minute delay has passed. This prevents you from getting multiple notifications for the same message from a user.

**Comment by bentettmar** [comment]
Okay, but in the code no where does it stop the notifications from being sent. All i can see is the time being added to a dictionary. If you could send a video of this working that would be great since im unable to test this as i dont have a windows computer to hand.

**Comment by bentettmar** [comment]
Yeh i see, you should be able to add another commit to this pull request by pushing it to your branch that was made in your fork.

**Comment by jbsparrow** [comment]
Uhh I already closed it 😧

**Comment by jbsparrow** [comment]
Awesome, and the commit is there!

**Comment by timof121** [comment]
it no worke

**Comment by timof121** [comment]
i dont get notification

**Comment by jbsparrow** [comment]
I just tested and it worked.

**Comment by jbsparrow** [comment]
I'll check the code again I guess

**Comment by bentettmar** [comment]
CleanShot 2022-06-15 at 7 30 38@2x
In theory this is what the results should look like when inspecting the code.

**Comment by timof121** [comment]
ok it worke

**Comment by jbsparrow** [comment]
Perfect

**Comment by bentettmar** [comment]
@jbsparrow do you have a discord?

**Comment by jbsparrow** [comment]
Yes - jbsparrow#5747

**Pull request merged**
