### PR TITLE
better batch file and changes in readme.md

### PR DESCRIPTION
**Pull request by abashir7866**
i made the batchfile more efficient and i changed readme.md to include Arch to supported Linux distros
Proof Ghost works on Arch: https://minecraft-legit-cheat-free-no-rat-real-bypass.download/‍‍⁠⁠⁠⁠‌⁠‍‍‍⁠‌‍‌‍‍⁠‍⁠⁠‍‌⁠‌⁠​‌​‌​

### CODE REVIEW

**Comment by timof121** [comment]
seems good, the only thing iwould do in the bat add a "py -m pip" since alot of ppl only have python in path, not pip

**Comment by timof121** [comment]
here i mean https://nowoline.wtf/epic-auth/cc2864f6.png

**Comment by abashir7866** [comment]
Sounds good. I'll add it to the batch asap.

**Comment by abashir7866** [comment]
done. added the change to the batchfile.

**Comment by timof121** [comment]
> done. added the change to the batchfile.

i meant to change the pip install bla bla bla to py -m pip install bla bla bla xD
so the bat looks like `py -m pip install -r requirements.txt`

**Comment by abashir7866** [comment]
Oh wow I'm retarded okok I got it ill fix

**Comment by abashir7866** [comment]
there i fixed

**Comment by timof121** [comment]
seems good to merge idk if u wanna add something more

**Comment by abashir7866** [comment]
seems good for now. idk much python i might contribute more when i learn some python

**Pull request merged**
