### PR TITLE
Removed All Embeds

### PR DESCRIPTION
**Pull request by IMXNOOBX**
Since discord doesnt allow user accounts to send embeds any more i've removed all the embeds from the sb completely.

### CODE REVIEW

**Comment by timof121** [comment]
why'd u waste ur life like that

**Comment by timof121** [comment]
you can just force text mode which I already did on dev branch

**Comment by IMXNOOBX** [comment]
Just to have a cleaner code, It doesn't help anyone being there

**Comment by bentettmar** [comment]
No point though. Forcing textmode is more efficient and since the code is already bad there isnt much point. New commands will just forget the is __embedmode__ from now on anyway.

**Pull request closed without merging**
