### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BobIsMyManager**
mfw it works on all distros before i found out it did

### CODE REVIEW

**Comment by abashir7866** [comment]
Goddammit you beat me to it. I just tested it on fedora

**Comment by timof121** [comment]
just tested on diofgovdkbducjjfuhkvuhh OS it works

**Comment by abashir7866** [comment]
Tested it on my grandpa's pacemaker it works

**Comment by BobIsMyManager** [comment]
just tested on mars rover and it worked

**Comment by bentettmar** [comment]
Working on Uranus

**Pull request merged**
