### PR TITLE
Typing Notifier Update

### PR DESCRIPTION
**Pull request by jbsparrow**
Updated the `on_typing` notifier so that it will wait two minutes before giving you another typing notification from the same user. This reduces the spam from the typing notifier greatly.

Other commits are because I don't have a great understanding of GitHub merging and pull requests, so hopefully this can be added without any trouble.

### CODE REVIEW

**Comment by timof121** [comment]
epic

**Comment by timof121** [comment]
@bentettmar shouldi  merge this

**Comment by Shkeffy** [comment]
Seems legit. 👍🏼

**Comment by jbsparrow** [comment]
I have no clue what you mean 😢

**Comment by 9qz** [comment]
for line in blabla:
    print(line.replace("ascii char", f"{Fore.blackperson}ascii char"))
something like that

**Comment by jbsparrow** [comment]
That's a much better way to colour the title, I might do that today.

**Comment by timof121** [comment]
can someone test this

**Comment by jbsparrow** [comment]
@timof121 I don't think anybody is testing it

**Comment by bentettmar** [comment]
@jbsparrow If you open a new pull requests correctly with only your commits/changes, ill take a look at it.

**Comment by timof121** [comment]
> > @jbsparrow If you open a new pull requests correctly with only your commits/changes, ill take a look at it.
> 
> What do you mean by only my commits/changes?

u had the mrege upsater mtheing

**Comment by jbsparrow** [comment]
> > > @jbsparrow If you open a new pull requests correctly with only your commits/changes, ill take a look at it.
> 
> > 
> 
> > What do you mean by only my commits/changes?
> 
> 
> 
> u had the mrege upsater mtheing

You all good?

**Comment by bentettmar** [comment]
If i was to merge this pull request it would add every other commit which may break the code and would be a pain to revert.

**Comment by jbsparrow** [comment]
Alright, I'll probably do that later today.

**Pull request closed without merging**
